runtime/controller: add flags to configure exponential back-off retry
fluxcd/pkg pull request #256
Opened 2022-04-11 15:14 UTC by pjbgf

Add two new flags to enable users to configure exponential back-off retry. 
The default values are set to 750ms for minimum retry time, and 15min for max.

2022-04-11 15:28 UTC, hiddeco approved these changes

2022-04-11 15:31 UTC, aryan9600 requested changes

2022-04-11 15:31 UTC, aryan9600 commented on runtime/controller/rate_limiter.go
> +		"The minimum amount of time in which a reconciliation object will wait before a retry.")
```suggestion
		"The minimum amount of time for which a reconciliation object will wait before a retry.")
```

2022-04-11 15:32 UTC, stefanprodan commented on runtime/controller/rate_limiter.go
> +		"The minimum amount of time in which a reconciliation object will wait before a retry.")
Maybe?
```suggestion
		"The minimum amount of time that an object reconciliation will wait before a retry.")
```

2022-04-12 07:24 UTC, merged

2022-04-12 07:26 UTC, stefanprodan commented
@pjbgf this was publish in `runtime/v0.14.0`